kind: Service
apiVersion: v1
metadata:
  name: rqliteviewer-service
spec:
  selector:
    juju-app-name: rqliteviewer
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30001
  type: NodePort
