#!/bin/bash

set -eu

hostname=`relation-get hostname`
port=`relation-get port`

[ -z "$hostname" ] && exit
[ -z "$port" ] && exit



list-units --format yaml | while read line; do
    unit=`echo $line | cut -d : -f1 | cut -d / -f2`
    kill-container $unit
    run-container $unit "app.py $hostname $port" "" "mikemccracken/rqliteviewer"
done
